export const HTTP_STATUS = {
	OK: 200,
	CREATED: 201,
	BAD_REQUEST: 400,
	UNAUTHORIZED: 401,
	FORBIDDEN: 403,
	NOT_FOUND: 404,
	CONFLICT: 409,
	UNPROCESSABLE_ENTITY: 422,
	INTERNAL_SERVER_ERROR: 500
};

export const ERROR_CODES = {
	VALIDATION_ERROR: 'VALIDATION_ERROR',
	UNAUTHENTICATED: 'UNAUTHENTICATED',
	UNAUTHORIZED: 'UNAUTHORIZED',
	NOT_FOUND: 'NOT_FOUND',
	CONFLICT: 'CONFLICT',
	INTERNAL_ERROR: 'INTERNAL_ERROR',
	SUCCESS: 'OK'
};

export const APP_CONFIG = {
	JWT_EXPIRES_IN: '24h',
	DEFAULT_PAGINATION_LIMIT: 20,
	BCRYPT_SALT_ROUNDS: 10
};

export const STORE_CONSTANTS = {
	PROMO_SHIPPING_CODE: 'XYZPROMOSHIPPING',
	SHIPPING_RATES: {
		GOSEND: 20000,
		JNE: 70000
	}
};
