export const ERROR_CODES = {
	VALIDATION_ERROR: 'VALIDATION_ERROR',
	INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
	UNAUTHENTICATED: 'UNAUTHENTICATED',
	UNAUTHORIZED: 'UNAUTHORIZED',
	NOT_FOUND: 'NOT_FOUND',
	CONFLICT: 'CONFLICT',
	INTERNAL_ERROR: 'INTERNAL_ERROR',
	DB_DUPLICATE_ENTRY: 'ER_DUP_ENTRY'
} as const;
